name: My first Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Chekout repo
          uses: actions/checkout@v4

        - name: List and Read files
          run: |
            echo "My first Github Actions Job"
            ls -ltrha
            cat README.md



        # - name: List files
        #  run: ls

        #- name: Read file
        #  run: cat README.md
