name: Workflow filters and activities

on: 
    workflow_dispatch:
    push:
      branches:
        - main
        - '!feature/*'
    
    pull_request:
      types:
        - opened
        - closed
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo this workflow/job/step is executed for event type - ${{ github.event_name}}